In [ ]:
print 'Hello World'

In [ ]:
print ('Hello World')

In [ ]:
print("Hello World")

In [ ]:
import keyword

In [ ]:
print (keyword.kwlist)

In [ ]:
len(keyword.kwlist)

In [ ]:
a, b, _, _ = 1, 'potter', 23, 43

In [ ]:
a, b

In [ ]:
x, _, y, _ = 1, 2, 3, 4

In [ ]:
x, y

In [ ]:
a = b = c =2.17

In [ ]:
a,b,c

In [ ]:
# to get input from the user
user_input = raw_input("Give me some input!: ")

# Numpy

A numpy array is a grid of values, all of the same type and is is indexed by a tuple of non-negative integers. 

The number of dimensions is the RANK of the array.

The SHAPE of the array is a tuple of integers giving the size of the array along each dimension.


In [3]:
import numpy as np

In [21]:
a = np.array([1,2,3])  # creates RANK 1 array

In [22]:
a

array([1, 2, 3])

In [23]:
print(type(a))

<type 'numpy.ndarray'>


In [24]:
print(a.shape)

(3,)


In [25]:
print(a)

[1 2 3]


In [26]:
print(a[0], a[1], a[2])

(1, 2, 3)


In [27]:
a[0]

1

In [28]:
a[1] = 123445

In [29]:
a

array([     1, 123445,      3])

In [15]:
print(a)

[     1 123445      3]


In [30]:
a[1] = 15

In [31]:
print(a)

[ 1 15  3]


In [32]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
print(b.shape)

(2, 3)


In [34]:
print(b[0, 0])

1


In [36]:
print(b[1,2])

6


In [39]:
m_npZEROS = np.zeros((2,2))

In [42]:
m_npZEROS

array([[ 0.,  0.],
       [ 0.,  0.]])

In [40]:
m_npONES = np.ones((3,3))

In [41]:
m_npONES

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [54]:
m_npFULL = np.full((4,5), 17, dtype='int64')

In [55]:
m_npFULL

array([[17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17]])

In [60]:
m_npEYE = np.eye(3, 4)

In [61]:
m_npEYE

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [62]:
m_npEYE = np.eye(3, 4, 1)

In [63]:
m_npEYE

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [64]:
m_npEYE = np.eye(3, 4, -1)

In [65]:
m_npEYE

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

In [74]:
m_npRANDOM = np.random.random((2,2))
m_npRANDOM

array([[ 0.77683136,  0.96197286],
       [ 0.23386338,  0.54167597]])

In [75]:
m_npRANDOM = np.random.random((2,2))
m_npRANDOM

array([[ 0.07241208,  0.8651905 ],
       [ 0.64797112,  0.66805613]])

In [76]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [78]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [5 6]]


A slice of the array is a view into the same data,
so modifying the slice will also modify the original array

In [79]:
print(a[1,1])

5


In [81]:
print(b[1, 0])
b[1,0] = 100
print(b[1,0])
print(a[1,1])


5
100
100


In [82]:
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [83]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

(array([  4, 100,   6]), (3,))
(array([[  4, 100,   6]]), (1, 3))


In [87]:
(np.eye(4)).shape

(4, 4)

In [88]:
a = [[1,2,3], [4,5,6]]

In [89]:
print(a)

[[1, 2, 3], [4, 5, 6]]


In [96]:
b = a[1]

In [97]:
b

[4, 5, 6]

In [98]:
b = a[:]

In [99]:
b

[[1, 2, 3], [4, 5, 6]]

In [100]:
b = [[10,20,30], [40,50,60]]

In [101]:
a

[[1, 2, 3], [4, 5, 6]]

In [102]:
b

[[10, 20, 30], [40, 50, 60]]

In [104]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
# integer array indexing
x = a[[0,1,2], [0,1,0]]
print(x)
print(x.shape)

[1 4 5]
(3,)


In [112]:
# slicing
y = np.array([a[0,0], a[1,1], a[2,0]])
print(y)
print(y.shape)

[1 4 5]
(3,)


In [113]:
# selcting/mutating one element from each row of a matrix

In [114]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [117]:
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [118]:
b = np.array([1,2,0,1])

In [119]:
b

array([1, 2, 0, 1])

In [120]:
print(a[np.arange(0,4), b])

[ 2  6  7 11]


In [121]:
print(a[np.arange(0,4), b])

[ 2  6  7 11]


In [125]:
a[np.arange(0,4),b] +=100

In [126]:
a

array([[  1, 102,   3],
       [  4,   5, 106],
       [107,   8,   9],
       [ 10, 111,  12]])

----------------------------------
**Boolean array indexing** lets us pick out *arbitrary* elements of an array.

This type of indexing is used to slect the elements of an array that satisfy some condition.

In [127]:
a = np.array([[1,2],[3,4],[5,6]])

In [128]:
bool_idx = (a>2)

In [129]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [132]:
#boolean indexing: It produces a Rank 1 array

print(a[bool_idx])

[3 4 5 6]


In [133]:
print(a[a>3])

[4 5 6]


In [162]:
m_list = [1,2,3]
m_npARRAY = np.array([1,2,3])

In [163]:
for e in m_list:
    print e

1
2
3


In [164]:
for e in m_npARRAY:
    print e

1
2
3


In [165]:
m_list.append(4)

In [166]:
m_list

[1, 2, 3, 4]

In [167]:
m_npARRAY.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [168]:
m_list += [5]
m_list

[1, 2, 3, 4, 5]

In [169]:
m_npARRAY += [5]
m_npARRAY

array([6, 7, 8])

In [170]:
m_list += [6,7]
m_list

[1, 2, 3, 4, 5, 6, 7]

In [171]:
m_npARRAY += [6,7]

ValueError: operands could not be broadcast together with shapes (3,) (2,) (3,) 

In [172]:
m_npARRAY + m_npARRAY

array([12, 14, 16])

In [175]:
print m_npARRAY
print m_npARRAY * 2

[6 7 8]
[12 14 16]


In [176]:
print(m_list)
print(m_list * 2)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]


In [179]:
print(m_npARRAY)
print(m_npARRAY ** 2)

[6 7 8]
[36 49 64]


In [180]:
print(m_npARRAY)
print(np.sqrt(m_npARRAY))

[6 7 8]
[ 2.44948974  2.64575131  2.82842712]


In [181]:
print(m_list)
print(np.sqrt(m_list))

[1, 2, 3, 4, 5, 6, 7]
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131]


In [183]:
print(m_npARRAY)
print(np.log(m_npARRAY))

[6 7 8]
[ 1.79175947  1.94591015  2.07944154]


In [184]:
print(m_npARRAY)
print(np.exp(m_npARRAY))

[6 7 8]
[  403.42879349  1096.63315843  2980.95798704]


In [185]:
a = np.array([1,21,32])
b = np.array([1,32,12])

In [192]:
dot = 0

In [193]:
for i,j in zip(a,b):
    dot += i*j

In [194]:
print(dot)

1057


In [195]:
a*b

array([  1, 672, 384])

In [196]:
print(np.sum(a*b))

1057


In [198]:
print((a*b).sum())

1057


In [199]:
print(np.dot(a,b))

1057


In [200]:
a.dot(b)

1057

In [201]:
b.dot(a)

1057

In [202]:
amag = np.sqrt((a*a).sum())

In [203]:
amag

38.288379438153292

In [204]:
amag = np.linalg.norm(a)

In [205]:
amag

38.288379438153292

In [208]:
cosAngle = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [209]:
cosAngle

0.80742231238276452

In [210]:
angle = np.arccos(cosAngle)      #in radians

In [211]:
angle

0.63102652242709534

In [217]:
# comparing numpy with default python functions

import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a,b):
    result = 0
    for e,f in zip(a,b):
        result += e*f

    return result

t0 = datetime.now()
for t in xrange(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in xrange(T):
    a.dot(b)
dt2 = datetime.now() - t0

print("dt1/dt2 = ", dt1.total_seconds()/dt2.total_seconds())


('dt1/dt2 = ', 46.810391397849465)


In [218]:
z = np.zeros(10)

In [219]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [222]:
z = np.zeros((10,10))
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [223]:
o = np.ones(10)
o

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [224]:
o = np.ones((10,10))
o

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [228]:
g = np.random.randn(10,10)
g


array([[ 0.30556723, -0.1531275 ,  1.19291898,  0.48458369, -0.72897641,
         0.28585452, -0.21835187,  0.39588094,  0.65607383,  2.25691262],
       [-0.06112422,  0.96084338, -2.27175282,  0.84154091, -0.45821689,
        -0.25728358,  1.4231254 , -0.22497451, -0.03872762,  0.10148863],
       [ 1.95354128, -1.26067869, -0.48947522, -0.90116875,  0.15685221,
         0.73581953, -1.31858192,  0.43964525, -1.2037121 ,  0.34599614],
       [ 0.7225117 ,  0.93685261,  1.99027255, -0.15483398,  1.00717345,
         0.43961153,  1.35710297,  0.65442207, -0.32017961, -2.00464066],
       [ 2.48467117,  1.35841446, -0.8417843 ,  2.1483636 , -2.04129163,
         2.81500931,  0.40514439, -0.7404707 , -0.69350867,  0.01082942],
       [ 0.32256786,  1.12359219, -0.35952796,  0.91359959,  0.67130493,
         0.11632338,  0.4597404 , -0.26557472, -0.33523262,  1.29439663],
       [-0.74931744,  0.98927081, -1.51396123, -1.56737393, -2.41032701,
        -1.08549081,  1.32096941, -0.46477151

In [229]:
r = np.random.random((10,10))
r

array([[ 0.04417262,  0.78878866,  0.64738479,  0.41933427,  0.23297596,
         0.60374701,  0.13303651,  0.61399152,  0.06032676,  0.72596034],
       [ 0.65631028,  0.18564054,  0.73036826,  0.1584487 ,  0.86423559,
         0.32833263,  0.64195941,  0.30367103,  0.4910578 ,  0.99453912],
       [ 0.40833616,  0.42310628,  0.31754052,  0.81724942,  0.42830543,
         0.26370308,  0.51605959,  0.80857603,  0.26615087,  0.42996778],
       [ 0.00409192,  0.69426659,  0.47060381,  0.45295957,  0.70751741,
         0.38636617,  0.35533598,  0.60368459,  0.87706015,  0.75117202],
       [ 0.75082573,  0.89923491,  0.52320782,  0.20751083,  0.69220652,
         0.19820559,  0.1613816 ,  0.69758144,  0.46762863,  0.19913196],
       [ 0.77375253,  0.76039427,  0.46083   ,  0.74190246,  0.62274427,
         0.41929709,  0.8541328 ,  0.29924972,  0.44872283,  0.44008921],
       [ 0.889279  ,  0.69877566,  0.00283783,  0.70629851,  0.08700888,
         0.98550186,  0.05826325,  0.00389588

In [231]:
print(g.mean())
print(g.var())

0.09207842683
1.14471571591


In [232]:
print(r.mean())
print(r.var())

0.511823563683
0.0748171805665


In [233]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [234]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [236]:
A.dot(Ainv)

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])

In [237]:
A*Ainv

array([[-2. ,  2. ],
       [ 4.5, -2. ]])

In [238]:
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [239]:
np.linalg.det(A)

-2.0000000000000004

In [240]:
np.linalg.det(Ainv)

-0.49999999999999967

In [241]:
np.linalg.det(A.dot(Ainv))

0.99999999999999956

In [243]:

print(A)
np.diag(A)

[[1 2]
 [3 4]]


array([1, 4])

In [244]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [245]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [246]:
a = np.array([1,2])
b = np.array([3,4])

In [247]:
print(np.outer(a,b))
print(np.inner(a,b))
print(a.dot(b))

[[3 4]
 [6 8]]
11
11


In [248]:
np.diag(A).sum()

5

In [249]:
np.trace(A)

5

In [250]:
x = np.random.randn(100,3)

In [251]:
x

array([[  1.08825394e+00,   5.09026055e-01,  -8.61654289e-01],
       [ -1.09044329e+00,   4.02756855e-01,   2.19663114e+00],
       [ -1.18715575e+00,   8.62518002e-01,   9.95845730e-01],
       [ -1.71443589e+00,   9.07127073e-01,  -1.01707887e+00],
       [ -7.33422177e-01,   2.58834309e-01,   9.73379163e-01],
       [  7.72904550e-01,   1.74969293e+00,  -4.24550770e-01],
       [ -4.86450082e-01,   6.79040400e-01,  -7.32902189e-01],
       [  4.66321607e-01,  -8.48679044e-01,   1.13598058e+00],
       [  1.84131850e-01,   1.30721579e-01,  -5.73870282e-01],
       [ -2.42389550e-01,   1.28013053e+00,   1.77606962e+00],
       [ -7.53520760e-01,  -1.39147301e+00,   1.56678099e+00],
       [  2.85079164e-01,   1.65257109e+00,   1.71103305e+00],
       [ -1.10078262e-01,  -1.94583679e+00,   5.92135871e-01],
       [  4.39320998e-01,  -1.52226134e+00,  -1.10256422e+00],
       [  8.32422850e-01,   6.39365102e-01,  -6.57658761e-01],
       [ -1.04042345e+00,   5.95342835e-01,   1.5403677

In [252]:
cov = np.cov(x)
cov

array([[ 1.00273527, -1.62220414, -0.93777174, ..., -0.53458614,
         0.12423111, -0.53133445],
       [-1.62220414,  2.70874832,  1.74590578, ...,  0.6395461 ,
        -0.32821199,  0.73930133],
       [-0.93777174,  1.74590578,  1.4974057 , ..., -0.11094046,
        -0.46117748,  0.17076971],
       ..., 
       [-0.53458614,  0.6395461 , -0.11094046, ...,  0.88654484,
         0.27348309,  0.60441863],
       [ 0.12423111, -0.32821199, -0.46117748, ...,  0.27348309,
         0.20724104,  0.11553734],
       [-0.53133445,  0.73930133,  0.17076971, ...,  0.60441863,
         0.11553734,  0.45300045]])

In [253]:
cov.shape

(100, 100)

In [254]:
cov = np.cov(x.T)

In [255]:
cov

array([[ 0.8028042 ,  0.01146894,  0.01574303],
       [ 0.01146894,  0.90513939,  0.06903582],
       [ 0.01574303,  0.06903582,  0.98193194]])

In [256]:
cov.shape

(3, 3)

In [257]:
np.linalg.eigh(cov)

(array([ 0.80105047,  0.8645972 ,  1.02422786]),
 array([[ 0.99574687,  0.02968233,  0.08721891],
        [-0.06994009,  0.85975936,  0.50588756],
        [-0.05997135, -0.50983605,  0.85817868]]))

In [258]:
np.linalg.eig(cov)

(array([ 1.02422786,  0.80105047,  0.8645972 ]),
 array([[ 0.08721891,  0.99574687, -0.02968233],
        [ 0.50588756, -0.06994009, -0.85975936],
        [ 0.85817868, -0.05997135,  0.50983605]]))

In [260]:
#linear system
# Ax = b
#=> A-1.A.x = 0 
#=> x = A-1.b

In [261]:
A

array([[1, 2],
       [3, 4]])

In [262]:
b

array([3, 4])

In [263]:
b = np.array([1,2])

In [264]:
b

array([1, 2])

In [265]:
x = np.linalg.inv(A).dot(b)
print(x)

[ 0.   0.5]


In [267]:
x = np.linalg.solve(A,b)
print(x)

[ 0.   0.5]


In [268]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

x = np.linalg.solve(A,b)
print(x)

[ 1500.   700.]


In [271]:
Y = []
Y

[]

In [278]:
Y = []
for line in open("data_2d.csv"):
    row = line.split(',')
    sample = map(float, row)
    Y.append(sample)

Y = np.array(Y)
print(Y)

[[  1.79302012e+01   9.45205920e+01   3.20259530e+02]
 [  9.71446972e+01   6.95932820e+01   4.04634472e+02]
 [  8.17759008e+01   5.73764810e+00   1.81485108e+02]
 [  5.58543424e+01   7.03259017e+01   3.21773638e+02]
 [  4.93665500e+01   7.51140402e+01   3.22465486e+02]
 [  3.19270247e+00   2.92562989e+01   9.46188109e+01]
 [  4.92007841e+01   8.61444385e+01   3.56348093e+02]
 [  2.18828039e+01   4.68415052e+01   1.81653769e+02]
 [  7.95098627e+01   8.73973555e+01   4.23557743e+02]
 [  8.81538875e+01   6.52056419e+01   3.69229245e+02]
 [  6.07438543e+01   9.99576339e+01   4.27605804e+02]
 [  6.74155819e+01   5.03683096e+01   2.92471822e+02]
 [  4.83181158e+01   9.91289531e+01   3.95529811e+02]
 [  2.88299720e+01   8.71849489e+01   3.19031348e+02]
 [  4.38537427e+01   6.44736391e+01   2.87428144e+02]
 [  2.53136941e+01   8.35452943e+01   2.92768909e+02]
 [  1.08077267e+01   4.56955686e+01   1.59663308e+02]
 [  9.83657459e+01   8.26973935e+01   4.38798964e+02]
 [  2.91469100e+01   6.63651

In [279]:
Y.shape

(100, 3)

In [281]:
import matplotlib.pyplot as plt

In [284]:
import pandas as pd

ImportError: C extension: iNaT not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

In [1]:
import pandas as pd

In [2]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Linux
OS-release: 4.13.0-26-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_IN
LOCALE: None.None

pandas: 0.20.2
pytest: 2.8.7
pip: 9.0.1
setuptools: 20.7.0
Cython: None
numpy: 1.14.0
scipy: 1.0.0
xarray: None
IPython: 5.5.0
sphinx: None
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.0
openpyxl: 2.3.0
xlrd: 0.9.4
xlwt: 0.7.5
xlsxwriter: None
lxml: 3.5.0
bs4: 4.4.1
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None


In [1]:
import pandas as pd

In [2]:
Y = pd.read_csv("data_2d.csv", header=None)

In [3]:
Y

0          1           2
0   17.930201  94.520592  320.259530
1   97.144697  69.593282  404.634472
2   81.775901   5.737648  181.485108
3   55.854342  70.325902  321.773638
4   49.366550  75.114040  322.465486
5    3.192702  29.256299   94.618811
6   49.200784  86.144439  356.348093
7   21.882804  46.841505  181.653769
8   79.509863  87.397356  423.557743
9   88.153887  65.205642  369.229245
10  60.743854  99.957634  427.605804
11  67.415582  50.368310  292.471822
12  48.318116  99.128953  395.529811
13  28.829972  87.184949  319.031348
14  43.853743  64.473639  287.428144
15  25.313694  83.545294  292.768909
16  10.807727  45.695569  159.663308
17  98.365746  82.697394  438.798964
18  29.146910  66.365107  250.986309
19  65.100302  33.353883  231.711508
20  24.644113  39.540053  163.398161
21  37.559805   1.345728   83.480155
22  88.164506  95.153663  466.265806
23  13.834621  25.494048  100.886430
24  64.410844  77.259838  365.641048
25  68.925992  97.453601  426.140015
26  39.488442  50.856128  235.532389
27  52.463178  59.776510  283.291640
28  48.484787  66.970354  298.581440
29   8.062088  98.242600  309.234109
..        ...        ...         ...
70  30.187692   7.146539   89.539008
71  11.788418  51.697761  181.550683
72  18.292424  61.977976  224.773383
73  96.712668   9.029102  219.567094
74  31.012739  78.283382  298.490216
75  11.397261  61.728693  199.944045
76  17.392556   4.241141   43.915692
77  72.182694  34.539072  256.068378
78  73.980021   3.716493  159.372581
79  94.493058  88.417197  447.132704
80  84.562821  20.241162  233.078830
81  51.742474  11.009748  131.070180
82  53.748590  60.025102  298.814333
83  85.050835  95.736997  451.803523
84  46.777250  90.202206  368.366436
85  49.758434  52.834494  254.706774
86  24.119257  42.102811  168.308433
87  27.201576  29.978749  146.342260
88   7.009596  55.876058  176.810149
89  97.646950   8.147625  219.160280
90   1.382983  84.944087  252.905653
91  22.323530  27.515075  127.570479
92  45.045406  93.520402  375.822340
93  40.163991   0.161699   80.389019
94  53.182740   8.170316  142.718183
95  46.456779  82.000171  336.876154
96  77.130301  95.188759  438.460586
97  68.600608  72.571181  355.900287
98  41.693887  69.241126  284.834637
99   4.142669  52.254726  168.034401

[100 rows x 3 columns]

In [4]:
type(Y)

pandas.core.frame.DataFrame

In [5]:
Y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB


In [6]:
Y.head()

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486

In [7]:
Y.head(9)

0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486
5   3.192702  29.256299   94.618811
6  49.200784  86.144439  356.348093
7  21.882804  46.841505  181.653769
8  79.509863  87.397356  423.557743

In [8]:
Y[0]

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...    
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, Length: 100, dt

In [9]:
type(Y[0])

pandas.core.series.Series

In [10]:
Y.iloc[0]

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [12]:
Y.ix[0]

0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64

In [13]:
Y[[0,2]]

0           2
0   17.930201  320.259530
1   97.144697  404.634472
2   81.775901  181.485108
3   55.854342  321.773638
4   49.366550  322.465486
5    3.192702   94.618811
6   49.200784  356.348093
7   21.882804  181.653769
8   79.509863  423.557743
9   88.153887  369.229245
10  60.743854  427.605804
11  67.415582  292.471822
12  48.318116  395.529811
13  28.829972  319.031348
14  43.853743  287.428144
15  25.313694  292.768909
16  10.807727  159.663308
17  98.365746  438.798964
18  29.146910  250.986309
19  65.100302  231.711508
20  24.644113  163.398161
21  37.559805   83.480155
22  88.164506  466.265806
23  13.834621  100.886430
24  64.410844  365.641048
25  68.925992  426.140015
26  39.488442  235.532389
27  52.463178  283.291640
28  48.484787  298.581440
29   8.062088  309.234109
..        ...         ...
70  30.187692   89.539008
71  11.788418  181.550683
72  18.292424  224.773383
73  96.712668  219.567094
74  31.012739  298.490216
75  11.397261  199.944045
76  17.392556   43.915692
77  72.182694  256.068378
78  73.980021  159.372581
79  94.493058  447.132704
80  84.562821  233.078830
81  51.742474  131.070180
82  53.748590  298.814333
83  85.050835  451.803523
84  46.777250  368.366436
85  49.758434  254.706774
86  24.119257  168.308433
87  27.201576  146.342260
88   7.009596  176.810149
89  97.646950  219.160280
90   1.382983  252.905653
91  22.323530  127.570479
92  45.045406  375.822340
93  40.163991   80.389019
94  53.182740  142.718183
95  46.456779  336.876154
96  77.130301  438.460586
97  68.600608  355.900287
98  41.693887  284.834637
99   4.142669  168.034401

[100 rows x 2 columns]

In [14]:
Y[ Y[0] < 5 ]

0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
54  4.593463  46.335932  145.818745
90  1.382983  84.944087  252.905653
99  4.142669  52.254726  168.034401

In [15]:
Y[0] < 5

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
      ...  
70    False
71    False
72    False
73    False
74    False
75    False
76    False
77    False
78    False
79    False
80    False
81    False
82    False
83    False
84    False
85    False
86    False
87    False
88    False
89    False
90     True
91    False
92    False
93    False
94    False
95    False
96    False
97    False
98    False
99     True
Name: 0, Length: 100, dtype: bool

In [16]:
type(Y[0] < 5)

pandas.core.series.Series

In [17]:
df = pd.read_csv("international-airline-passengers.csv", engine="python", skipfooter=3)

In [18]:
df

Month  \
0    1949-01   
1    1949-02   
2    1949-03   
3    1949-04   
4    1949-05   
5    1949-06   
6    1949-07   
7    1949-08   
8    1949-09   
9    1949-10   
10   1949-11   
11   1949-12   
12   1950-01   
13   1950-02   
14   1950-03   
15   1950-04   
16   1950-05   
17   1950-06   
18   1950-07   
19   1950-08   
20   1950-09   
21   1950-10   
22   1950-11   
23   1950-12   
24   1951-01   
25   1951-02   
26   1951-03   
27   1951-04   
28   1951-05   
29   1951-06   
..       ...   
114  1958-07   
115  1958-08   
116  1958-09   
117  1958-10   
118  1958-11   
119  1958-12   
120  1959-01   
121  1959-02   
122  1959-03   
123  1959-04   
124  1959-05   
125  1959-06   
126  1959-07   
127  1959-08   
128  1959-09   
129  1959-10   
130  1959-11   
131  1959-12   
132  1960-01   
133  1960-02   
134  1960-03   
135  1960-04   
136  1960-05   
137  1960-06   
138  1960-07   
139  1960-08   
140  1960-09   
141  1960-10   
142  1960-11   
143  1960-12   

     International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60  
0                                                  112                               
1                                                  118                               
2                                                  132                               
3                                                  129                               
4                                                  121                               
5                                                  135                               
6                                                  148                               
7                                                  148                               
8                                                  136                               
9                                                  119                               
10                                                 104                               
11                                                 118                               
12                                                 115                               
13                                                 126                               
14                                                 141                               
15                                                 135                               
16                                                 125                               
17                                                 149                               
18                                                 170                               
19                                                 170                               
20                                                 158                               
21                                                 133                               
22                                                 114                               
23                                                 140                               
24                                                 145                               
25                                                 150                               
26                                                 178                               
27                                                 163                               
28                                                 172                               
29                                                 178                               
..                                                 ...                               
114                                                491                               
115                                                505                               
116                                                404                               
117 

In [20]:
df.columns

Index([u'Month', u'International airline passengers: monthly totals in thousands. Jan 49 ? Dec 60'], dtype='object')

In [21]:
df.columns = ['month', 'passangers']

In [22]:
df.columns

Index([u'month', u'passangers'], dtype='object')

In [23]:
df

month  passangers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
5    1949-06         135
6    1949-07         148
7    1949-08         148
8    1949-09         136
9    1949-10         119
10   1949-11         104
11   1949-12         118
12   1950-01         115
13   1950-02         126
14   1950-03         141
15   1950-04         135
16   1950-05         125
17   1950-06         149
18   1950-07         170
19   1950-08         170
20   1950-09         158
21   1950-10         133
22   1950-11         114
23   1950-12         140
24   1951-01         145
25   1951-02         150
26   1951-03         178
27   1951-04         163
28   1951-05         172
29   1951-06         178
..       ...         ...
114  1958-07         491
115  1958-08         505
116  1958-09         404
117  1958-10         359
118  1958-11         310
119  1958-12         337
120  1959-01         360
121  1959-02         342
122  1959-03         406
123  1959-04         396
124  1959-05         420
125  1959-06         472
126  1959-07         548
127  1959-08         559
128  1959-09         463
129  1959-10         407
130  1959-11         362
131  1959-12         405
132  1960-01         417
133  1960-02         391
134  1960-03         419
135  1960-04         461
136  1960-05         472
137  1960-06         535
138  1960-07         622
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [25]:
df['passangers']

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
      ... 
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
143    432
Name: passangers, Length: 144, dtype: int64

In [27]:
df.passangers

0      112
1      118
2      132
3      129
4      121
5      135
6      148
7      148
8      136
9      119
10     104
11     118
12     115
13     126
14     141
15     135
16     125
17     149
18     170
19     170
20     158
21     133
22     114
23     140
24     145
25     150
26     178
27     163
28     172
29     178
      ... 
114    491
115    505
116    404
117    359
118    310
119    337
120    360
121    342
122    406
123    396
124    420
125    472
126    548
127    559
128    463
129    407
130    362
131    405
132    417
133    391
134    419
135    461
136    472
137    535
138    622
139    606
140    508
141    461
142    390
143    432
Name: passangers, Length: 144, dtype: int64

In [28]:
df['ones'] = 1

In [29]:
df.head()

month  passangers  ones
0  1949-01         112     1
1  1949-02         118     1
2  1949-03         132     1
3  1949-04         129     1
4  1949-05         121     1

In [34]:
from datetime import datetime
datetime.strptime("2018-05", "%Y-%m")
df['x1x2'] = df.apply(lambda row: datetime.strptime(row["month"], "%Y-%m"), axis=1)

In [35]:
df.head()

month  passangers  ones       x1x2
0  1949-01         112     1 1949-01-01
1  1949-02         118     1 1949-02-01
2  1949-03         132     1 1949-03-01
3  1949-04         129     1 1949-04-01
4  1949-05         121     1 1949-05-01

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 4 columns):
month         144 non-null object
passangers    144 non-null int64
ones          144 non-null int64
x1x2          144 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 4.6+ KB


In [38]:
t1 = pd.read_csv("table1.csv")
t2 = pd.read_csv("table2.csv")

In [39]:
t1

user_id            email  age
0        1  alice@gmail.com   20
1        2    bob@gmail.com   25
2        3  carol@gmail.com   30

In [40]:
t2

user_id  ad_id  click
0         1      1      1
1         1      2      0
2         1      5      0
3         2      3      0
4         2      4      1
5         2      1      0
6         3      2      0
7         3      1      0
8         3      3      0
9         3      4      0
10        3      5      1

In [41]:
type(t1)

pandas.core.frame.DataFrame

In [44]:
m = pd.merge(t1,t2,on='user_id')

In [45]:
m

user_id            email  age  ad_id  click
0         1  alice@gmail.com   20      1      1
1         1  alice@gmail.com   20      2      0
2         1  alice@gmail.com   20      5      0
3         2    bob@gmail.com   25      3      0
4         2    bob@gmail.com   25      4      1
5         2    bob@gmail.com   25      1      0
6         3  carol@gmail.com   30      2      0
7         3  carol@gmail.com   30      1      0
8         3  carol@gmail.com   30      3      0
9         3  carol@gmail.com   30      4      0
10        3  carol@gmail.com   30      5      1