In [ ]:
print 'Hello World'

In [ ]:
print ('Hello World')

In [ ]:
print("Hello World")

In [ ]:
import keyword

In [ ]:
print (keyword.kwlist)

In [ ]:
len(keyword.kwlist)

In [ ]:
a, b, _, _ = 1, 'potter', 23, 43

In [ ]:
a, b

In [ ]:
x, _, y, _ = 1, 2, 3, 4

In [ ]:
x, y

In [ ]:
a = b = c =2.17

In [ ]:
a,b,c

In [ ]:
# to get input from the user
user_input = raw_input("Give me some input!: ")

# Numpy

A numpy array is a grid of values, all of the same type and is is indexed by a tuple of non-negative integers. 

The number of dimensions is the RANK of the array.

The SHAPE of the array is a tuple of integers giving the size of the array along each dimension.


In [3]:
import numpy as np

In [21]:
a = np.array([1,2,3])  # creates RANK 1 array

In [22]:
a

array([1, 2, 3])

In [23]:
print(type(a))

<type 'numpy.ndarray'>


In [24]:
print(a.shape)

(3,)


In [25]:
print(a)

[1 2 3]


In [26]:
print(a[0], a[1], a[2])

(1, 2, 3)


In [27]:
a[0]

1

In [28]:
a[1] = 123445

In [29]:
a

array([     1, 123445,      3])

In [15]:
print(a)

[     1 123445      3]


In [30]:
a[1] = 15

In [31]:
print(a)

[ 1 15  3]


In [32]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
print(b.shape)

(2, 3)


In [34]:
print(b[0, 0])

1


In [36]:
print(b[1,2])

6


In [39]:
m_npZEROS = np.zeros((2,2))

In [42]:
m_npZEROS

array([[ 0.,  0.],
       [ 0.,  0.]])

In [40]:
m_npONES = np.ones((3,3))

In [41]:
m_npONES

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [54]:
m_npFULL = np.full((4,5), 17, dtype='int64')

In [55]:
m_npFULL

array([[17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17]])

In [60]:
m_npEYE = np.eye(3, 4)

In [61]:
m_npEYE

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [62]:
m_npEYE = np.eye(3, 4, 1)

In [63]:
m_npEYE

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [64]:
m_npEYE = np.eye(3, 4, -1)

In [65]:
m_npEYE

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

In [74]:
m_npRANDOM = np.random.random((2,2))
m_npRANDOM

array([[ 0.77683136,  0.96197286],
       [ 0.23386338,  0.54167597]])

In [75]:
m_npRANDOM = np.random.random((2,2))
m_npRANDOM

array([[ 0.07241208,  0.8651905 ],
       [ 0.64797112,  0.66805613]])

In [76]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [78]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [5 6]]


A slice of the array is a view into the same data,
so modifying the slice will also modify the original array

In [79]:
print(a[1,1])

5


In [81]:
print(b[1, 0])
b[1,0] = 100
print(b[1,0])
print(a[1,1])


5
100
100


In [82]:
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [83]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

(array([  4, 100,   6]), (3,))
(array([[  4, 100,   6]]), (1, 3))


In [87]:
(np.eye(4)).shape

(4, 4)

In [88]:
a = [[1,2,3], [4,5,6]]

In [89]:
print(a)

[[1, 2, 3], [4, 5, 6]]


In [96]:
b = a[1]

In [97]:
b

[4, 5, 6]

In [98]:
b = a[:]

In [99]:
b

[[1, 2, 3], [4, 5, 6]]

In [100]:
b = [[10,20,30], [40,50,60]]

In [101]:
a

[[1, 2, 3], [4, 5, 6]]

In [102]:
b

[[10, 20, 30], [40, 50, 60]]

In [104]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
# integer array indexing
x = a[[0,1,2], [0,1,0]]
print(x)
print(x.shape)

[1 4 5]
(3,)


In [112]:
# slicing
y = np.array([a[0,0], a[1,1], a[2,0]])
print(y)
print(y.shape)

[1 4 5]
(3,)


In [113]:
# selcting/mutating one element from each row of a matrix

In [114]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [117]:
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [118]:
b = np.array([1,2,0,1])

In [119]:
b

array([1, 2, 0, 1])

In [120]:
print(a[np.arange(0,4), b])

[ 2  6  7 11]


In [121]:
print(a[np.arange(0,4), b])

[ 2  6  7 11]


In [125]:
a[np.arange(0,4),b] +=100

In [126]:
a

array([[  1, 102,   3],
       [  4,   5, 106],
       [107,   8,   9],
       [ 10, 111,  12]])

----------------------------------
**Boolean array indexing** lets us pick out *arbitrary* elements of an array.

This type of indexing is used to slect the elements of an array that satisfy some condition.

In [127]:
a = np.array([[1,2],[3,4],[5,6]])

In [128]:
bool_idx = (a>2)

In [129]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [132]:
#boolean indexing: It produces a Rank 1 array

print(a[bool_idx])

[3 4 5 6]


In [133]:
print(a[a>3])

[4 5 6]


In [162]:
m_list = [1,2,3]
m_npARRAY = np.array([1,2,3])

In [163]:
for e in m_list:
    print e

1
2
3


In [164]:
for e in m_npARRAY:
    print e

1
2
3


In [165]:
m_list.append(4)

In [166]:
m_list

[1, 2, 3, 4]

In [167]:
m_npARRAY.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [168]:
m_list += [5]
m_list

[1, 2, 3, 4, 5]

In [169]:
m_npARRAY += [5]
m_npARRAY

array([6, 7, 8])

In [170]:
m_list += [6,7]
m_list

[1, 2, 3, 4, 5, 6, 7]

In [171]:
m_npARRAY += [6,7]

ValueError: operands could not be broadcast together with shapes (3,) (2,) (3,) 

In [172]:
m_npARRAY + m_npARRAY

array([12, 14, 16])

In [175]:
print m_npARRAY
print m_npARRAY * 2

[6 7 8]
[12 14 16]


In [176]:
print(m_list)
print(m_list * 2)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]


In [179]:
print(m_npARRAY)
print(m_npARRAY ** 2)

[6 7 8]
[36 49 64]


In [180]:
print(m_npARRAY)
print(np.sqrt(m_npARRAY))

[6 7 8]
[ 2.44948974  2.64575131  2.82842712]


In [181]:
print(m_list)
print(np.sqrt(m_list))

[1, 2, 3, 4, 5, 6, 7]
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131]


In [183]:
print(m_npARRAY)
print(np.log(m_npARRAY))

[6 7 8]
[ 1.79175947  1.94591015  2.07944154]


In [184]:
print(m_npARRAY)
print(np.exp(m_npARRAY))

[6 7 8]
[  403.42879349  1096.63315843  2980.95798704]


In [185]:
a = np.array([1,21,32])
b = np.array([1,32,12])

In [192]:
dot = 0

In [193]:
for i,j in zip(a,b):
    dot += i*j

In [194]:
print(dot)

1057


In [195]:
a*b

array([  1, 672, 384])

In [196]:
print(np.sum(a*b))

1057


In [198]:
print((a*b).sum())

1057


In [199]:
print(np.dot(a,b))

1057


In [200]:
a.dot(b)

1057

In [201]:
b.dot(a)

1057

In [202]:
amag = np.sqrt((a*a).sum())

In [203]:
amag

38.288379438153292

In [204]:
amag = np.linalg.norm(a)

In [205]:
amag

38.288379438153292

In [208]:
cosAngle = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [209]:
cosAngle

0.80742231238276452

In [210]:
angle = np.arccos(cosAngle)      #in radians

In [211]:
angle

0.63102652242709534

In [217]:
# comparing numpy with default python functions

import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a,b):
    result = 0
    for e,f in zip(a,b):
        result += e*f

    return result

t0 = datetime.now()
for t in xrange(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in xrange(T):
    a.dot(b)
dt2 = datetime.now() - t0

print("dt1/dt2 = ", dt1.total_seconds()/dt2.total_seconds())


('dt1/dt2 = ', 46.810391397849465)


In [218]:
z = np.zeros(10)

In [219]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [222]:
z = np.zeros((10,10))
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [223]:
o = np.ones(10)
o

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [224]:
o = np.ones((10,10))
o

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [228]:
g = np.random.randn(10,10)
g


array([[ 0.30556723, -0.1531275 ,  1.19291898,  0.48458369, -0.72897641,
         0.28585452, -0.21835187,  0.39588094,  0.65607383,  2.25691262],
       [-0.06112422,  0.96084338, -2.27175282,  0.84154091, -0.45821689,
        -0.25728358,  1.4231254 , -0.22497451, -0.03872762,  0.10148863],
       [ 1.95354128, -1.26067869, -0.48947522, -0.90116875,  0.15685221,
         0.73581953, -1.31858192,  0.43964525, -1.2037121 ,  0.34599614],
       [ 0.7225117 ,  0.93685261,  1.99027255, -0.15483398,  1.00717345,
         0.43961153,  1.35710297,  0.65442207, -0.32017961, -2.00464066],
       [ 2.48467117,  1.35841446, -0.8417843 ,  2.1483636 , -2.04129163,
         2.81500931,  0.40514439, -0.7404707 , -0.69350867,  0.01082942],
       [ 0.32256786,  1.12359219, -0.35952796,  0.91359959,  0.67130493,
         0.11632338,  0.4597404 , -0.26557472, -0.33523262,  1.29439663],
       [-0.74931744,  0.98927081, -1.51396123, -1.56737393, -2.41032701,
        -1.08549081,  1.32096941, -0.46477151

In [229]:
r = np.random.random((10,10))
r

array([[ 0.04417262,  0.78878866,  0.64738479,  0.41933427,  0.23297596,
         0.60374701,  0.13303651,  0.61399152,  0.06032676,  0.72596034],
       [ 0.65631028,  0.18564054,  0.73036826,  0.1584487 ,  0.86423559,
         0.32833263,  0.64195941,  0.30367103,  0.4910578 ,  0.99453912],
       [ 0.40833616,  0.42310628,  0.31754052,  0.81724942,  0.42830543,
         0.26370308,  0.51605959,  0.80857603,  0.26615087,  0.42996778],
       [ 0.00409192,  0.69426659,  0.47060381,  0.45295957,  0.70751741,
         0.38636617,  0.35533598,  0.60368459,  0.87706015,  0.75117202],
       [ 0.75082573,  0.89923491,  0.52320782,  0.20751083,  0.69220652,
         0.19820559,  0.1613816 ,  0.69758144,  0.46762863,  0.19913196],
       [ 0.77375253,  0.76039427,  0.46083   ,  0.74190246,  0.62274427,
         0.41929709,  0.8541328 ,  0.29924972,  0.44872283,  0.44008921],
       [ 0.889279  ,  0.69877566,  0.00283783,  0.70629851,  0.08700888,
         0.98550186,  0.05826325,  0.00389588

In [231]:
print(g.mean())
print(g.var())

0.09207842683
1.14471571591


In [232]:
print(r.mean())
print(r.var())

0.511823563683
0.0748171805665


In [233]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [234]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [236]:
A.dot(Ainv)

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])

In [237]:
A*Ainv

array([[-2. ,  2. ],
       [ 4.5, -2. ]])

In [238]:
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [239]:
np.linalg.det(A)

-2.0000000000000004

In [240]:
np.linalg.det(Ainv)

-0.49999999999999967

In [241]:
np.linalg.det(A.dot(Ainv))

0.99999999999999956

In [243]:

print(A)
np.diag(A)

[[1 2]
 [3 4]]


array([1, 4])

In [244]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [245]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [246]:
a = np.array([1,2])
b = np.array([3,4])

In [247]:
print(np.outer(a,b))
print(np.inner(a,b))
print(a.dot(b))

[[3 4]
 [6 8]]
11
11


In [248]:
np.diag(A).sum()

5

In [249]:
np.trace(A)

5

In [250]:
x = np.random.randn(100,3)

In [251]:
x

array([[  1.08825394e+00,   5.09026055e-01,  -8.61654289e-01],
       [ -1.09044329e+00,   4.02756855e-01,   2.19663114e+00],
       [ -1.18715575e+00,   8.62518002e-01,   9.95845730e-01],
       [ -1.71443589e+00,   9.07127073e-01,  -1.01707887e+00],
       [ -7.33422177e-01,   2.58834309e-01,   9.73379163e-01],
       [  7.72904550e-01,   1.74969293e+00,  -4.24550770e-01],
       [ -4.86450082e-01,   6.79040400e-01,  -7.32902189e-01],
       [  4.66321607e-01,  -8.48679044e-01,   1.13598058e+00],
       [  1.84131850e-01,   1.30721579e-01,  -5.73870282e-01],
       [ -2.42389550e-01,   1.28013053e+00,   1.77606962e+00],
       [ -7.53520760e-01,  -1.39147301e+00,   1.56678099e+00],
       [  2.85079164e-01,   1.65257109e+00,   1.71103305e+00],
       [ -1.10078262e-01,  -1.94583679e+00,   5.92135871e-01],
       [  4.39320998e-01,  -1.52226134e+00,  -1.10256422e+00],
       [  8.32422850e-01,   6.39365102e-01,  -6.57658761e-01],
       [ -1.04042345e+00,   5.95342835e-01,   1.5403677

In [252]:
cov = np.cov(x)
cov

array([[ 1.00273527, -1.62220414, -0.93777174, ..., -0.53458614,
         0.12423111, -0.53133445],
       [-1.62220414,  2.70874832,  1.74590578, ...,  0.6395461 ,
        -0.32821199,  0.73930133],
       [-0.93777174,  1.74590578,  1.4974057 , ..., -0.11094046,
        -0.46117748,  0.17076971],
       ..., 
       [-0.53458614,  0.6395461 , -0.11094046, ...,  0.88654484,
         0.27348309,  0.60441863],
       [ 0.12423111, -0.32821199, -0.46117748, ...,  0.27348309,
         0.20724104,  0.11553734],
       [-0.53133445,  0.73930133,  0.17076971, ...,  0.60441863,
         0.11553734,  0.45300045]])

In [253]:
cov.shape

(100, 100)

In [254]:
cov = np.cov(x.T)

In [255]:
cov

array([[ 0.8028042 ,  0.01146894,  0.01574303],
       [ 0.01146894,  0.90513939,  0.06903582],
       [ 0.01574303,  0.06903582,  0.98193194]])

In [256]:
cov.shape

(3, 3)

In [257]:
np.linalg.eigh(cov)

(array([ 0.80105047,  0.8645972 ,  1.02422786]),
 array([[ 0.99574687,  0.02968233,  0.08721891],
        [-0.06994009,  0.85975936,  0.50588756],
        [-0.05997135, -0.50983605,  0.85817868]]))

In [258]:
np.linalg.eig(cov)

(array([ 1.02422786,  0.80105047,  0.8645972 ]),
 array([[ 0.08721891,  0.99574687, -0.02968233],
        [ 0.50588756, -0.06994009, -0.85975936],
        [ 0.85817868, -0.05997135,  0.50983605]]))

In [260]:
#linear system
# Ax = b
#=> A-1.A.x = 0 
#=> x = A-1.b

In [261]:
A

array([[1, 2],
       [3, 4]])

In [262]:
b

array([3, 4])

In [263]:
b = np.array([1,2])

In [264]:
b

array([1, 2])

In [265]:
x = np.linalg.inv(A).dot(b)
print(x)

[ 0.   0.5]


In [267]:
x = np.linalg.solve(A,b)
print(x)

[ 0.   0.5]


In [268]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

x = np.linalg.solve(A,b)
print(x)

[ 1500.   700.]
