In [ ]:
print 'Hello World'

In [ ]:
print ('Hello World')

In [ ]:
print("Hello World")

In [ ]:
import keyword

In [ ]:
print (keyword.kwlist)

In [ ]:
len(keyword.kwlist)

In [ ]:
a, b, _, _ = 1, 'potter', 23, 43

In [ ]:
a, b

In [ ]:
x, _, y, _ = 1, 2, 3, 4

In [ ]:
x, y

In [ ]:
a = b = c =2.17

In [ ]:
a,b,c

In [ ]:
# to get input from the user
user_input = raw_input("Give me some input!: ")

# Numpy

A numpy array is a grid of values, all of the same type and is is indexed by a tuple of non-negative integers. 

The number of dimensions is the RANK of the array.

The SHAPE of the array is a tuple of integers giving the size of the array along each dimension.


In [3]:
import numpy as np

In [21]:
a = np.array([1,2,3])  # creates RANK 1 array

In [22]:
a

array([1, 2, 3])

In [23]:
print(type(a))

<type 'numpy.ndarray'>


In [24]:
print(a.shape)

(3,)


In [25]:
print(a)

[1 2 3]


In [26]:
print(a[0], a[1], a[2])

(1, 2, 3)


In [27]:
a[0]

1

In [28]:
a[1] = 123445

In [29]:
a

array([     1, 123445,      3])

In [15]:
print(a)

[     1 123445      3]


In [30]:
a[1] = 15

In [31]:
print(a)

[ 1 15  3]


In [32]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
print(b.shape)

(2, 3)


In [34]:
print(b[0, 0])

1


In [36]:
print(b[1,2])

6


In [39]:
m_npZEROS = np.zeros((2,2))

In [42]:
m_npZEROS

array([[ 0.,  0.],
       [ 0.,  0.]])

In [40]:
m_npONES = np.ones((3,3))

In [41]:
m_npONES

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [54]:
m_npFULL = np.full((4,5), 17, dtype='int64')

In [55]:
m_npFULL

array([[17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17]])

In [60]:
m_npEYE = np.eye(3, 4)

In [61]:
m_npEYE

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [62]:
m_npEYE = np.eye(3, 4, 1)

In [63]:
m_npEYE

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [64]:
m_npEYE = np.eye(3, 4, -1)

In [65]:
m_npEYE

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

In [74]:
m_npRANDOM = np.random.random((2,2))
m_npRANDOM

array([[ 0.77683136,  0.96197286],
       [ 0.23386338,  0.54167597]])

In [75]:
m_npRANDOM = np.random.random((2,2))
m_npRANDOM

array([[ 0.07241208,  0.8651905 ],
       [ 0.64797112,  0.66805613]])

In [76]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [78]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [5 6]]


A slice of the array is a view into the same data,
so modifying the slice will also modify the original array

In [79]:
print(a[1,1])

5


In [81]:
print(b[1, 0])
b[1,0] = 100
print(b[1,0])
print(a[1,1])


5
100
100


In [82]:
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [83]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

(array([  4, 100,   6]), (3,))
(array([[  4, 100,   6]]), (1, 3))


In [87]:
(np.eye(4)).shape

(4, 4)

In [88]:
a = [[1,2,3], [4,5,6]]

In [89]:
print(a)

[[1, 2, 3], [4, 5, 6]]


In [96]:
b = a[1]

In [97]:
b

[4, 5, 6]

In [98]:
b = a[:]

In [99]:
b

[[1, 2, 3], [4, 5, 6]]

In [100]:
b = [[10,20,30], [40,50,60]]

In [101]:
a

[[1, 2, 3], [4, 5, 6]]

In [102]:
b

[[10, 20, 30], [40, 50, 60]]

In [104]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
# integer array indexing
x = a[[0,1,2], [0,1,0]]
print(x)
print(x.shape)

[1 4 5]
(3,)


In [112]:
# slicing
y = np.array([a[0,0], a[1,1], a[2,0]])
print(y)
print(y.shape)

[1 4 5]
(3,)


In [113]:
# selcting/mutating one element from each row of a matrix

In [114]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [117]:
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [118]:
b = np.array([1,2,0,1])

In [119]:
b

array([1, 2, 0, 1])

In [120]:
print(a[np.arange(0,4), b])

[ 2  6  7 11]


In [121]:
print(a[np.arange(0,4), b])

[ 2  6  7 11]


In [125]:
a[np.arange(0,4),b] +=100

In [126]:
a

array([[  1, 102,   3],
       [  4,   5, 106],
       [107,   8,   9],
       [ 10, 111,  12]])

----------------------------------
**Boolean array indexing** lets us pick out *arbitrary* elements of an array.

This type of indexing is used to slect the elements of an array that satisfy some condition.

In [127]:
a = np.array([[1,2],[3,4],[5,6]])

In [128]:
bool_idx = (a>2)

In [129]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [132]:
#boolean indexing: It produces a Rank 1 array

print(a[bool_idx])

[3 4 5 6]


In [133]:
print(a[a>3])

[4 5 6]
